#!/usr/bin/env perl
use 5.018;
use strict;
use warnings;

use Test::More;

my $class = 'Hash';
use_ok( $class );
use Hash;

my $hash = new Hash();
isa_ok( $hash, $class );
can_ok( $hash, 'new'  );
can_ok( $hash, 'store' );
can_ok( $hash, 'fetch' );
can_ok( $hash, 'hash' );
can_ok( $hash, 'lookup' );

my @data = ( [qw(a A 97)],[qw(b B 98)],[qw(c C 99)] );

$hash->store( $_->[0], $_->[1] )                                                     foreach (@data);
ok( $hash->fetch( $_->[0] ) eq $_->[1], "fetch key >$_->[0]< with value >$_->[1]<" ) foreach (@data);
ok( !defined $hash->fetch("x"), 'fetch undefined key should be >undef<' );

ok( $hash->hash( $_->[0] ) == $_->[2], 'test hash method' ) foreach (@data);

ok( eq_array( $hash->lookup( 'a' ), [ undef, undef ] ), 'test $hash_1->lookup("key")' );


done_testing;
exit 0;
