#!/usr/bin/env perl
use 5.018;
use strict;
use warnings;

use Test::More;

my $class = 'Hash';
use_ok( $class );
use Hash;

my $hash = new Hash();
isa_ok( $hash, $class );
can_ok( $hash, 'new'  );
can_ok( $hash, 'store' );
can_ok( $hash, 'fetch' );

$hash->store("key", "value");
ok( $hash->fetch("key") eq "value", '$hash->fetch("key") eq "value"' );


done_testing;


exit 0;
